# Generated by Django 2.0.1 on 2018-01-22 14:45

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(editable=False, max_length=100)),
                ('path', models.CharField(editable=False, max_length=100, unique=True)),
                ('body', models.TextField(editable=False)),
                ('body_html', models.TextField(blank=True, editable=False)),
                ('status', models.IntegerField(default=2, editable=False)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.AlterModelManagers(
            name='page',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='pagehistory',
            name='page',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='pinax_pages.Page'),
        ),
    ]
