# Generated by Django 2.0.1 on 2018-01-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_pages', '0002_auto_20180122_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagehistory',
            name='path',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
